DEVICE: cuda

CHECKPOINTS_DIR: checkpoints
DFG_CHECKPOINTS_DIR: ${CHECKPOINTS_DIR}/dfg
ARCFACE_PRETRAINED_PATH: ${CHECKPOINTS_DIR}/arcface_pretrained.pth

LOGS_DIR: logs
DFG_LOG_FILE: ${LOGS_DIR}/dfg_training.log
DFG_EVAL_LOG_FILE: ${LOGS_DIR}/dfg_evaluation.log

RESULTS_DIR: results
VISUALIZATIONS_DIR: ${RESULTS_DIR}/visualizations
DFG_CUES_VIZ_DIR: ${VISUALIZATIONS_DIR}/dfg_generated_cues
DFG_EVAL_REPORT_FILE: ${RESULTS_DIR}/evaluation_reports/dfg_test_report.txt

DFG_BATCH_SIZE: 64
DFG_NUM_EPOCHS: 50
DFG_TOTAL_TRAINING_STEPS_REFERENCE: 150000
DFG_LEARNING_RATE: 0.00001
DFG_WEIGHT_DECAY: 0.01
DFG_BETAS: [0.9, 0.999]
DFG_MAX_DIFFUSION_STEPS: 1000
DFG_T_HAT_CUE_GENERATION: 800
DFG_EARLY_STOPPING_PATIENCE: 10
DFG_LR_SCHEDULER_FACTOR: 0.5
DFG_LR_SCHEDULER_PATIENCE: 7

DFG_EVAL_SAMPLES_TO_VIZ: 5