DEVICE: cuda

CHECKPOINTS_DIR: checkpoints
OANET_CHECKPOINTS_DIR: ${CHECKPOINTS_DIR}/oanet

LOGS_DIR: logs
OANET_LOG_FILE: ${LOGS_DIR}/oanet_training.log

RESULTS_DIR: results
VISUALIZATIONS_DIR: ${RESULTS_DIR}/visualizations
EVAL_REPORTS_DIR: ${RESULTS_DIR}/evaluation_reports
EVAL_RESULTS_FILE: ${EVAL_REPORTS_DIR}/oanet_test_report.txt

OANET_BATCH_SIZE: 128
OANET_NUM_EPOCHS: 50
OANET_LEARNING_RATE: 0.0001
OANET_BACKBONE_LR_FACTOR: 0.1
OANET_BETAS: [0.9, 0.999]
OANET_EARLY_STOPPING_PATIENCE: 10
OANET_LR_SCHEDULER_FACTOR: 0.5
OANET_LR_SCHEDULER_PATIENCE: 10

OANET_EVAL_THRESHOLD: 0.5